### ISSUE TITLE
@James-Yu Dev TODO Note

### ISSUE THREAD

**Issue by James-Yu** [James-Yu/LaTeX-Workshop#3609]
This is a mega-issue recording the feature and refactor TODOs to be implemented by @James-Yu in the near future. Hope I have the time to finish the rosy picture.

- [ ] (#3604) Better tests
- [ ] More intellisense tests
- [ ] More intellisense implementation for tests
- [ ] More structure view configurations
- [ ] Better and concise extension log
